config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    root "restaurants#index"
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restautant.rb
class Restautant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end


end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :authenticate_admin
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    def authenticate_admin
      unless current_user.admin?
        flash[:alert] = "Not allow!"
        redirect_to root_path
      end
    end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!
  before_action :authenticate_admin

  def index
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/index.html.erb
<h1>餐廳後台</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li>
    <%= restaurant.name %>
    <%= link_to 'Show', admin_restaurant_path(restaurant) %>
    <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
    <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: {confirm:"Are you sure?"} %>
  </li>
    <% end %>
</ul>
<%= link_to 'New restaurant', new_admin_restaurant_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
    Hi, <%= current_user.email %>
      <%= link_to('登出', destroy_user_session_path, method: :delete) %> |
      <%= link_to('修改密碼', edit_user_registration_path) %>
    <% else %>
      <%= link_to('註冊', new_user_registration_path) %> |
      <%= link_to('登入', new_user_session_path) %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>餐廳前台</h1>